"""Compile local JSON + PNG/JPEG content into a bounded immutable firmware package.

Uses Pillow; never writes SPI Flash/SD or changes model preprocessing.
"""
from pathlib import Path
import argparse,json,zlib,hashlib,platform,tempfile,os
import PIL
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
def require(condition,message):
    if not condition: raise ValueError(message)
def unique_object(pairs):
    result={}
    for key,value in pairs:
        require(key not in result,'Duplicate JSON key: '+key)
        result[key]=value
    return result
def atomic_write(path,payload):
    # Each replacement is atomic. The sidecar hash detects interruption between
    # the two replacements; build verification must reject a mismatched pair.
    with tempfile.NamedTemporaryFile(dir=path.parent,delete=False) as stream:
        temporary=Path(stream.name);stream.write(payload)
    try:os.replace(temporary,path)
    finally:temporary.unlink(missing_ok=True)
def compile_content(source,destination):
    p=Path(source).resolve();out=Path(destination).resolve();evidence_path=out.with_suffix('.json')
    require(out!=p and evidence_path!=p and out!=evidence_path,'Output/manifest must not overwrite source or each other')
    data=json.loads(p.read_text(encoding='utf-8'),object_pairs_hook=unique_object)
    require(data['schema_version']==1 and isinstance(data['version'],str),'Unsupported package version')
    groups=data['collections'];require(isinstance(groups,list) and 1<=len(groups)<=8,'Expected 1..8 collections')
    lines=['/* Generated by Tools/deploy_v5_content.py; do not edit. */','#include "gs_content.h"']
    images=[];evidence=[];total_pixels=0;text_bytes=0;non_ascii=set()
    def text(s):
        nonlocal text_bytes
        require(isinstance(s,str) and 0<len(s)<=512 and all(ord(c)>=32 or c in '\n\r\t' for c in s),'Invalid text')
        text_bytes+=len(s.encode('utf-8'));require(text_bytes<=32768,'Text exceeds 32 KiB content budget')
        non_ascii.update(c for c in s if ord(c)>126)
        return json.dumps(s,ensure_ascii=False)
    for ci,g in enumerate(groups):
        require(isinstance(g['pages'],list) and 1<=len(g['pages'])<=32,'Expected 1..32 pages')
        for pi,page in enumerate(g['pages']):
            if 'image' not in page:continue
            f=(p.parent/page['image']).resolve();require(f.is_relative_to(p.parent),'Image path escapes package')
            require(f!=out and f!=evidence_path,'Output must not overwrite an input image')
            with Image.open(f) as image:
                require(image.format in ('PNG','JPEG') and 0<image.width<=320 and 0<image.height<=180,'Expected PNG/JPEG up to 320x180')
                total_pixels+=image.width*image.height*2
                require(total_pixels<=524288,'Images exceed 512 KiB internal-flash content budget')
                image=image.convert('RGB')
                raw=bytearray()
                pixels=image.get_flattened_data() if hasattr(image,'get_flattened_data') else image.getdata()
                for r,green,b in pixels:
                    value=((r>>3)<<11)|((green>>2)<<5)|(b>>3);raw.extend(value.to_bytes(2,'big'))
                w,h=image.size
            name=f'pixels_{ci}_{pi}'
            lines.append(f'static const uint8_t {name}[]={{')
            lines += [','.join(str(v) for v in raw[i:i+32])+',' for i in range(0,len(raw),32)]
            lines.append('};')
            crc=zlib.crc32(raw);images.append(f'{{{ci},{pi},{w},{h},{name},{len(raw)}U,0x{crc:08x}U}}')
            evidence.append({'file':str(f),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'raw_sha256':hashlib.sha256(raw).hexdigest(),'raw_crc32':crc,'bytes':len(raw)})
        lines.append(f'static const gs_ui_page_t pages_{ci}[]={{')
        lines += ['{'+text(page['title'])+','+text(page['body'])+'},' for page in g['pages']]
        lines.append('};')
    require(len(images)<=16,'At most 16 images')
    lines.append('static const gs_ui_collection_t collections[]={')
    lines += ['{'+text(g['title'])+f',{len(g["pages"])},pages_{i},GS_UI_COLLECTION_CONTENT,'+text(g.get('author','佚名'))+'},' for i,g in enumerate(groups)]
    lines.append('};')
    if images:lines.extend(['static const gs_content_image_t images[]={',',\n'.join(images),'};'])
    lines.append('const gs_content_package_t g_gs_content_builtin_package={'+text(data['version'])+f',collections,{len(groups)},{len(images)},'+('images' if images else 'NULL')+'};')
    out.parent.mkdir(parents=True,exist_ok=True);payload=('\n'.join(lines)+'\n').encode('utf-8')
    metadata={'source':str(p),'source_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'python':platform.python_version(),'pillow':PIL.__version__,'pixel_policy':'encoded orientation, RGB conversion drops alpha without compositing, first frame','images':evidence,'image_bytes':total_pixels,'text_bytes':text_bytes,'non_ascii_requires_font_check':sorted(non_ascii),'generated_sha256':hashlib.sha256(payload).hexdigest()}
    atomic_write(out,payload);atomic_write(evidence_path,json.dumps(metadata,indent=2).encode('utf-8'))
    if non_ascii: print('Font coverage must be checked for: '+''.join(sorted(non_ascii)))
    print(f'Compiled {len(groups)} collections / {len(images)} images into {out}')
if __name__=='__main__':
    a=argparse.ArgumentParser();a.add_argument('--source',type=Path,default=ROOT/'Assets/content/package.json');a.add_argument('--output',type=Path,default=ROOT/'Modules/Content/Src/gs_content_builtin.c');args=a.parse_args()
    compile_content(args.source,args.output)
