"""Integrate the selected CubeF4 lwIP core; do not edit its upstream sources.

Run after integrate.py / CubeMX generation. --prepare-only copies the SDK and
creates the tiny compiler arch header without touching the Keil project (useful
for independent compilation while another worker regenerates the project).
Only one StorageTask may call the NO_SYS port in BSP/Src/gs_ethernet.c.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
REL = Path("Middlewares/Third_Party/LwIP")
GROUP = "GestureScreen/LwIP"
ARCH_CC = r'''/* Generated by Tools/integrate_lwip.py. Application compiler port;
 * this is not a modification of the SDK's system/arch/cc.h.
 * AC6 has GCC-style packed attributes; do not include the SDK port's
 * GNU-host sys/time.h path or its returning printf-only assertion macro. */
#ifndef GS_LWIP_ARCH_CC_H
#define GS_LWIP_ARCH_CC_H
#include <stdint.h>
#include <stddef.h>
typedef int sys_prot_t;
void gs_lwip_assert(const char *file, unsigned line);
uint32_t gs_lwip_rand(void);
#define BYTE_ORDER LITTLE_ENDIAN
#define PACK_STRUCT_BEGIN
#define PACK_STRUCT_END
#define PACK_STRUCT_STRUCT __attribute__((packed))
#define PACK_STRUCT_FIELD(x) x
#define LWIP_PLATFORM_DIAG(message) do { } while (0)
#define LWIP_PLATFORM_ASSERT(message) gs_lwip_assert(__FILE__, __LINE__)
#define LWIP_RAND() gs_lwip_rand()
#define LWIP_TIMEVAL_PRIVATE 1
#endif
'''


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def sdk_path() -> Path:
    values = dict(line.split("=", 1) for line in
                  (ROOT / "GestureScreen.ioc").read_text(encoding="utf-8").splitlines()
                  if "=" in line)
    return Path(values["ProjectManager.CustomerFirmwarePackage"]
                .replace("\\:", ":").replace("\\\\", "\\"))


def source_list(destination: Path) -> list[Path]:
    return [*sorted((destination / "src/core").glob("*.c")),
            *sorted((destination / "src/core/ipv4").glob("*.c")),
            destination / "src/netif/ethernet.c"]


def prepare(sdk: Path) -> list[Path]:
    source = sdk / REL
    destination = ROOT / REL
    if not (source / "src/include/lwip/init.h").is_file():
        raise FileNotFoundError(f"CubeF4 lwIP sources not found: {source}")
    # Copy the upstream tree with its licenses/docs. No system OS port is
    # compiled; gs_port/arch/cc.h is selected before any SDK system include.
    for entry in source.rglob("*"):
        if entry.is_file():
            target = destination / entry.relative_to(source)
            if not target.is_file() or digest(entry) != digest(target):
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(entry, target)
    arch = destination / "gs_port/arch/cc.h"
    arch.parent.mkdir(parents=True, exist_ok=True)
    if not arch.is_file() or arch.read_text(encoding="utf-8") != ARCH_CC:
        arch.write_text(ARCH_CC, encoding="utf-8", newline="\n")
    sources = source_list(destination)
    manifest = {
        "sdk": str(sdk),
        "source": str(source),
        "profile": "NO_SYS=1; one StorageTask; raw TCP; IPv4 static LAN",
        "compiled_sources": {p.relative_to(ROOT).as_posix(): digest(p) for p in sources},
        "arch_header": arch.relative_to(ROOT).as_posix(),
        "arch_sha256": digest(arch),
    }
    record = ROOT / "Build/lwip-source-manifest.json"
    record.parent.mkdir(parents=True, exist_ok=True)
    record.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return sources


def integrate(sources: list[Path]) -> None:
    project = ROOT / "MDK-ARM/GestureScreen.uvprojx"
    tree = ET.parse(project)
    targets = tree.findall("./Targets/Target")
    if len(targets) != 1 or targets[0].findtext("TargetName") != "GestureScreen":
        raise ValueError("Expected exactly the GestureScreen Keil target")
    target = targets[0]
    groups = target.find("Groups")
    assert groups is not None
    for group in list(groups):
        if group.findtext("GroupName") == GROUP:
            groups.remove(group)
        elif "lwip" in (group.findtext("GroupName") or "").lower():
            raise ValueError("Another lwIP group exists: remove duplicate CubeMX OS port before integration")
    group = ET.SubElement(groups, "Group")
    ET.SubElement(group, "GroupName").text = GROUP
    files = ET.SubElement(group, "Files")
    for path in sources:
        entry = ET.SubElement(files, "File")
        ET.SubElement(entry, "FileName").text = path.name
        ET.SubElement(entry, "FileType").text = "1"
        ET.SubElement(entry, "FilePath").text = "../" + path.relative_to(ROOT).as_posix()
    include = target.find("./TargetOption/TargetArmAds/Cads/VariousControls/IncludePath")
    assert include is not None
    existing = [value for value in (include.text or "").split(";") if value]
    custom = ["../BSP/Inc", "../Middlewares/Third_Party/LwIP/gs_port",
              "../Middlewares/Third_Party/LwIP/src/include"]
    include.text = ";".join(dict.fromkeys(custom + existing))
    ET.indent(tree, space="  ")
    temporary = project.with_suffix(".lwip.tmp")
    tree.write(temporary, encoding="utf-8", xml_declaration=True)
    temporary.replace(project)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args()
    sdk = sdk_path()
    sources = prepare(sdk)
    if not args.prepare_only:
        integrate(sources)
    print(f"Prepared {len(sources)} original lwIP core/IPv4/Ethernet sources from {sdk.name}.")
    print("NO_SYS port: StorageTask only; no tcpip.c, sys_arch.c, sockets or netconn.")
    if not args.prepare_only:
        print("Updated GestureScreen Keil group and include paths.")


if __name__ == "__main__":
    main()
