#ifndef GS_MEMORY_MAP_H
#define GS_MEMORY_MAP_H

/* SDRAM 固定分区，不分配链接区；实际初始化由 gs_port_board.c 完成。
 * 依据：挑战者 V1 的 IS42S16400J，FMC SDRAM Bank2，8 MiB、16 位。
 * 800×480 RGB565：2026-09-15 用户确认野火配套屏，仍待上板验收。
 * 来源：plans/A5-... 第 4.2 节及 research/a5-camera-hardware/v1_bsp_sdram.h。
 * 
 * 本头文件仅定义整数常量与编译期检查，不创建数组、解引用宏或访问 SDRAM。
 * C 运行库通常先于 FMC 初始化执行，不能把普通零初始化对象放到这些地址。
 * 启动时的 .data/.bss、栈和 RTOS 堆保留在片内 RAM。BSP 完成 SDRAM 初始化
 * 及测试后，再显式初始化分区，向 Camera/Display 和独立 GUI 分配器提供指针。
 * 
 * 每个预留区只有一个所有者；通用 SDRAM 堆不能覆盖图像或 I/O 分区。
 * Camera、LTDC、DMA2D 和 SDIO DMA 缓冲禁止使用 CCM。
 * 32 字节对齐是本项目的分区约定，不是 F7/H7 的 D-cache 维护要求；目标是 F429。 */

#define GS_SDRAM_BASE_ADDR            0xD0000000UL
#define GS_SDRAM_CAPACITY_BYTES       0x00800000UL
#define GS_SDRAM_ALIGNMENT_BYTES      32UL
#define GS_SDRAM_BUDGET_LIMIT_BYTES   0x00400000UL

#define GS_LCD_REFERENCE_WIDTH       800UL
#define GS_LCD_REFERENCE_HEIGHT      480UL
#define GS_LCD_BYTES_PER_PIXEL       2UL
#define GS_CAMERA_REFERENCE_WIDTH    320UL
#define GS_CAMERA_REFERENCE_HEIGHT   240UL
#define GS_CAMERA_BYTES_PER_PIXEL    2UL

#define GS_SDRAM_LCD_FRAME_BYTES           0x000BB800UL
#define GS_SDRAM_CAMERA_FRAME_BYTES        0x00025800UL
#define GS_GUI_STRIP_BYTES           0x00010000UL
#define GS_ASSET_CACHE_BYTES         0x00100000UL
#define GS_GRAPHICS_SCRATCH_BYTES    0x00020000UL
#define GS_STORAGE_IO_BYTES          0x00020000UL
#define GS_GUI_HEAP_BYTES            0x0000C000UL

/* 本参考布局采用固定偏移。调整任一分区大小时，必须复核后续偏移、显示尺寸和总预算。 */
#define GS_LCD_BUFFER0_OFFSET        0x00000000UL
#define GS_LCD_BUFFER1_OFFSET        0x000BB800UL
#define GS_CAMERA_BUFFER0_OFFSET     0x00177000UL
#define GS_CAMERA_BUFFER1_OFFSET     0x0019C800UL
#define GS_GUI_STRIP0_OFFSET         0x001C2000UL
#define GS_GUI_STRIP1_OFFSET         0x001D2000UL
#define GS_ASSET_CACHE_OFFSET        0x001E2000UL
#define GS_GRAPHICS_SCRATCH_OFFSET   0x002E2000UL
#define GS_STORAGE_IO_OFFSET         0x00302000UL
#define GS_GUI_HEAP_OFFSET           0x00322000UL

#define GS_LCD_BUFFER0_ADDR       (GS_SDRAM_BASE_ADDR + GS_LCD_BUFFER0_OFFSET)
#define GS_LCD_BUFFER1_ADDR       (GS_SDRAM_BASE_ADDR + GS_LCD_BUFFER1_OFFSET)
#define GS_CAMERA_BUFFER0_ADDR    (GS_SDRAM_BASE_ADDR + GS_CAMERA_BUFFER0_OFFSET)
#define GS_CAMERA_BUFFER1_ADDR    (GS_SDRAM_BASE_ADDR + GS_CAMERA_BUFFER1_OFFSET)
#define GS_GUI_STRIP0_ADDR        (GS_SDRAM_BASE_ADDR + GS_GUI_STRIP0_OFFSET)
#define GS_GUI_STRIP1_ADDR        (GS_SDRAM_BASE_ADDR + GS_GUI_STRIP1_OFFSET)
#define GS_ASSET_CACHE_ADDR       (GS_SDRAM_BASE_ADDR + GS_ASSET_CACHE_OFFSET)
#define GS_GRAPHICS_SCRATCH_ADDR  (GS_SDRAM_BASE_ADDR + GS_GRAPHICS_SCRATCH_OFFSET)
#define GS_STORAGE_IO_ADDR        (GS_SDRAM_BASE_ADDR + GS_STORAGE_IO_OFFSET)
#define GS_GUI_HEAP_ADDR          (GS_SDRAM_BASE_ADDR + GS_GUI_HEAP_OFFSET)

/* CameraTask copies complete frames; StorageTask owns USB or Ethernet uploads.
 * These transports are selected exclusively in gs_capture_config.h. */
#define GS_UPLOAD_BUFFER0_OFFSET    0x00380000UL
#define GS_UPLOAD_BUFFER1_OFFSET    0x003A5800UL
#define GS_UPLOAD_BUFFER0_ADDR      (GS_SDRAM_BASE_ADDR + GS_UPLOAD_BUFFER0_OFFSET)
#define GS_UPLOAD_BUFFER1_ADDR      (GS_SDRAM_BASE_ADDR + GS_UPLOAD_BUFFER1_OFFSET)

#define GS_SDRAM_USED_BYTES          (GS_UPLOAD_BUFFER1_OFFSET + GS_SDRAM_CAMERA_FRAME_BYTES)
#define GS_SDRAM_BUDGET_SPARE_BYTES  (GS_SDRAM_BUDGET_LIMIT_BYTES - GS_SDRAM_USED_BYTES)
#define GS_SDRAM_PHYSICAL_FREE_BYTES (GS_SDRAM_CAPACITY_BYTES - GS_SDRAM_USED_BYTES)

#if GS_SDRAM_CAPACITY_BYTES != 0x00800000UL
#error "EmbedFire Challenger V1 has 8 MiB SDRAM; do not use Apollo or Challenger V2 geometry"
#endif

/* 使用预处理器断言，兼容 Arm Compiler 5/6 和主机 C99 编译器。 */
#if GS_SDRAM_LCD_FRAME_BYTES != (GS_LCD_REFERENCE_WIDTH * GS_LCD_REFERENCE_HEIGHT * GS_LCD_BYTES_PER_PIXEL)
#error "LCD frame size disagrees with reference pixel geometry"
#endif
#if GS_SDRAM_CAMERA_FRAME_BYTES != (GS_CAMERA_REFERENCE_WIDTH * GS_CAMERA_REFERENCE_HEIGHT * GS_CAMERA_BYTES_PER_PIXEL)
#error "Camera frame size disagrees with reference pixel geometry"
#endif

#if ((GS_SDRAM_BASE_ADDR | GS_LCD_BUFFER0_OFFSET | GS_LCD_BUFFER1_OFFSET | \
      GS_CAMERA_BUFFER0_OFFSET | GS_CAMERA_BUFFER1_OFFSET | \
      GS_GUI_STRIP0_OFFSET | GS_GUI_STRIP1_OFFSET | GS_ASSET_CACHE_OFFSET | \
      GS_GRAPHICS_SCRATCH_OFFSET | GS_STORAGE_IO_OFFSET | GS_GUI_HEAP_OFFSET | \
      GS_SDRAM_LCD_FRAME_BYTES | GS_SDRAM_CAMERA_FRAME_BYTES | GS_GUI_STRIP_BYTES | \
      GS_ASSET_CACHE_BYTES | GS_GRAPHICS_SCRATCH_BYTES | GS_STORAGE_IO_BYTES | \
      GS_GUI_HEAP_BYTES) & (GS_SDRAM_ALIGNMENT_BYTES - 1UL)) != 0UL
#error "Every SDRAM region start and size must be aligned to 32 bytes"
#endif

#if (GS_LCD_BUFFER0_OFFSET + GS_SDRAM_LCD_FRAME_BYTES > GS_LCD_BUFFER1_OFFSET) || \
    (GS_LCD_BUFFER1_OFFSET + GS_SDRAM_LCD_FRAME_BYTES > GS_CAMERA_BUFFER0_OFFSET) || \
    (GS_CAMERA_BUFFER0_OFFSET + GS_SDRAM_CAMERA_FRAME_BYTES > GS_CAMERA_BUFFER1_OFFSET) || \
    (GS_CAMERA_BUFFER1_OFFSET + GS_SDRAM_CAMERA_FRAME_BYTES > GS_GUI_STRIP0_OFFSET) || \
    (GS_GUI_STRIP0_OFFSET + GS_GUI_STRIP_BYTES > GS_GUI_STRIP1_OFFSET) || \
    (GS_GUI_STRIP1_OFFSET + GS_GUI_STRIP_BYTES > GS_ASSET_CACHE_OFFSET) || \
    (GS_ASSET_CACHE_OFFSET + GS_ASSET_CACHE_BYTES > GS_GRAPHICS_SCRATCH_OFFSET) || \
    (GS_GRAPHICS_SCRATCH_OFFSET + GS_GRAPHICS_SCRATCH_BYTES > GS_STORAGE_IO_OFFSET) || \
    (GS_STORAGE_IO_OFFSET + GS_STORAGE_IO_BYTES > GS_GUI_HEAP_OFFSET) || \
    (GS_GUI_HEAP_OFFSET + GS_GUI_HEAP_BYTES > GS_UPLOAD_BUFFER0_OFFSET) || \
    (GS_UPLOAD_BUFFER0_OFFSET + GS_SDRAM_CAMERA_FRAME_BYTES > GS_UPLOAD_BUFFER1_OFFSET)
#error "SDRAM reservations overlap or are not ordered"
#endif

#if (GS_SDRAM_USED_BYTES > GS_SDRAM_BUDGET_LIMIT_BYTES) || \
    (GS_SDRAM_BUDGET_LIMIT_BYTES > GS_SDRAM_CAPACITY_BYTES)
#error "SDRAM reservations exceed the 4 MiB budget or physical device"
#endif
#if (GS_SDRAM_BASE_ADDR > 0xFFFFFFFFUL - (GS_SDRAM_CAPACITY_BYTES - 1UL))
#error "SDRAM physical region exceeds the 32-bit address space"
#endif

#endif
